try:
    raise Exception("Shit")
except Exception as e:
    print("error was:", e)
